name: XXXXXX
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - cudatoolkit
  - tensorflow-gpu==2.8.0
  - pip:
      - tensorboardX
      - psutil
      - scikit-learn==0.23.2
      - opencv-python
      - pillow
      - matplotlib
