name: revi
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - cudatoolkit
  - scikit-learn==0.23.2
  - pip:
      - tensorboardX
      - psutil
      - opencv-python
      - pillow
      - matplotlib
      - tensorflow
      - carbontracker
